[book]
title = "Root14 Documentation"
authors = ["abhirupinspace"]
language = "en"
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Root-14/r14-dev"
